services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: workboard
      POSTGRES_USER: workboard
      POSTGRES_PASSWORD: workboard
    ports:
      - '54329:5432'
    volumes:
      - workboard-postgres:/var/lib/postgresql/data

volumes:
  workboard-postgres:
